Feature/account setting
its-dev-fer/project-spark pull request #7
Opened 2024-12-13 21:06 UTC by JhairAlexby1

2024-12-13 21:09 UTC, JhairAlexby1 commented
![iPhone-13-PRO-localhost](https://github.com/user-attachments/assets/5b50bfce-1272-415b-b7ac-f43a81c78b10)
<img width="578" alt="pc" src="https://github.com/user-attachments/assets/0828c546-212a-4f56-8090-60b759e8487e" />

2024-12-13 22:21 UTC, its-dev-fer requested changes

2024-12-13 22:21 UTC, its-dev-fer commented on src/components/settings/AccountSettingsForm.tsx
> +                placeholder="Contraseña"
"Confirma la contraseña"

2024-12-13 22:21 UTC, its-dev-fer commented on src/components/settings/AccountSettingsForm.tsx
> +        Guardar cambios
Se puede validar que el botón esté deshabilitado si el form no es válido?

2024-12-16 18:18 UTC, its-dev-fer requested changes

2024-12-16 18:18 UTC, its-dev-fer commented on package.json
`npm version patch`, por favor.

2024-12-16 18:20 UTC, JhairAlexby1 commented on package.json
listo

2024-12-16 19:38 UTC, its-dev-fer approved these changes

2024-12-16 19:41 UTC, Josep2506 approved these changes

2024-12-17 19:49 UTC, its-dev-fer approved these changes

2024-12-17 19:50 UTC, merged